name: Build Bicep

on:
    pull_request: 
        types: [opened, synchronize]

permissions:
    id-token: write
    contents: read
    security-events: write

jobs:
    build:
        name: 'Build Bicep'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: 'Az CLI login'
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Build
              uses: Azure/cli@v1
              with:
                inlineScript: |
                    az bicep build --file src/main.bicep --stdout