name: Deploy Infrastructure

on:
  workflow_dispatch: 
    inputs:
      location:
        required: true
        description: 'The location to deploy to'
        type: string
  push:
    branches: 
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  deploy_dev:
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      deployEnv: dev
      location: ${{ github.event.inputs.location }}
    secrets: inherit

  deploy_stg:
    needs: deploy_dev
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      deployEnv: stg
      location: ${{ github.event.inputs.location }}
    secrets: inherit

  deploy_prod:
    needs: deploy_stg
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      deployEnv: stg
      location: ${{ github.event.inputs.location }}
    secrets: inherit
