name: Deploy Infrastructure

on:
  push:
    branches: 
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  deploy_dev:
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      environment: dev
    secrets: inherit

  deploy_stg:
    needs: deploy_dev
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      environment: stg
    secrets: inherit

  deploy_prod:
    needs: deploy_stg
    uses: ./.github/workflows/shared.deploy_bicep.yaml
    with:
      environment: stg
    secrets: inherit